### ISSUE TITLE
Ignores keypresses, due to slow jumping to next field

### ISSUE THREAD

**Issue by onyxg** [fkranenburg/bootstrap-pincode-input#18]
There appears to be a problem when you type really fast on the desktop version (multiple input boxes)

**Comment by fkranenburg** [comment]
I can't reproduce. What browser are you using?

**Comment by fkranenburg** [comment]
I'm closing this since I still can't reproduce. Without any further information it is impossible to investigate this. To me it looks like a local browser / hardware related issue.
