### ISSUE TITLE
Why is the mobile configuration required?

### ISSUE THREAD

**Issue by ToothlessRebel** [fkranenburg/bootstrap-pincode-input#20]
Why did you choose a single input over a styled table to simulated the 4 inputs on mobile? Would not 4 styled inputs work?

**Comment by fkranenburg** [comment]
Yes I agree that would be better. If I remember correctly, this did not work nicely on ipad / iphone. For example if you type in a wrong number and you want to quickly fix it you can't just backspace it. You would have to manually activate the correct input box, select the value and replace it with a new value. There where a couple of other issues that I couldn't fix with multiple styled inputs.
