### ISSUE TITLE
After entering the last digit on a touch device, there are visual issues

### ISSUE THREAD

**Issue by simonbrueckner** [fkranenburg/bootstrap-pincode-input#24]
We have implemented the pincode input for touch devices and noticed that after entering the last digit, there are pretty visible jumps of the numbers which looks ugly (it doesn't affect functionality though).

See the attached video (it happens with the examples here as well: http://fkranenburg.github.io/bootstrap-pincode-input)

This happened on 1.7.0
[VID_20200205_151003.mp4.zip](https://github.com/fkranenburg/bootstrap-pincode-input/files/4160434/VID_20200205_151003.mp4.zip)

**Comment by fkranenburg** [comment]
You are right. I don't see this happening on Chrome (on a touch device), but I do on Firefox. I'll take a look at it.

**Comment by simonbrueckner** [comment]
Cool, thanks for your quick reply! I am seeing it on Safari Webkit on iOS - and to my understanding Apple enforces Webkit to be used in any browser on iOS (also Chrome and Firefox) - so effectively, the issue will occur on any iOS browser.

**Comment by fkranenburg** [comment]
The problem here is that I use `letter-spacing` to render all digits inside the textbox. The last digit also gets the letter-spacing. I have refactored some of the code to prevent this from happening. I didn't see this behaviour now in Firefox so hopefully it will fix this issue also. Please let me know.

**Comment by simonbrueckner** [comment]
Thanks a lot for the super fast fix. However, on iOS devices, the letter spacing now seems to be completely ignored on your demo page, see attached video (i tested on several devices to make sure its not a caching issues).
[RPReplay_Final1581019364.MP4.zip](https://github.com/fkranenburg/bootstrap-pincode-input/files/4167501/RPReplay_Final1581019364.MP4.zip)

**Comment by fkranenburg** [comment]
Ok, I think I fixed that. Could you check it out with latest version (v2.0.1)?

**Comment by simonbrueckner** [comment]
Wow, you're really quick! Now it's looking much better, thank you! There is a minimal glitch in the end, but it's a huge improvement to the state before and I could certainly live with it.

[RPReplay_Final1581019364.MP4.zip](https://github.com/fkranenburg/bootstrap-pincode-input/files/4167596/RPReplay_Final1581019364.MP4.zip)

**Comment by fkranenburg** [comment]
I'll dive into it later when I have more time. The issue looks like browser related: 
https://stackoverflow.com/a/6949953/1181067

For now this is the best I can do. The current way it works is just more of a workaround.

**Comment by simonbrueckner** [comment]
I was just doing some more tests, but for me, the issue is in fact not much improved with the latest fixes on iOS. As it is only a visual issue, I think we can leave it from here. Thanks for your effort, Ferry!
