### ISSUE TITLE
Null value when the PIN is pasted instead of typed - Chrome, Android

### ISSUE THREAD

**Issue by ayarse** [fkranenburg/bootstrap-pincode-input#28]
I'm getting a null value posted to my server when the PIN code is pasted in, instead of being typed in. 

I am using this plugin to let users enter an OTP. Since Android allows user to copy the code directly from the notification, a lot of users who were pasting it in using this method were getting their OTP invalidated. So I want through my logs to find out the the value for this field was null in the form data being submitted.

I have only tested on Chrome on Android but some of my iOS users have also reported the issue.

**Comment by fkranenburg** [comment]
I just tested this on Chrome on Android (9) and it works fine here. The only issue I see is that the numbers are a bit of, but no null values. When I paste the code and press enter, the value is correct. Could you reproduce in the first textbox of the [demopage ](http://fkranenburg.github.io/bootstrap-pincode-input/)?

**Comment by ayarse** [comment]
Able to reproduce on demo page.  (Chrome 80.0.3987.162 on Android 9.)

I was also able to reproduce on Safari on the iOS Simulator and mobile view in Chrome Devtools.

 Paste-ins can bypass maxlength limit and don't trigger the "complete" callback too. 
So I did a small hack and added a paste event listener that triggers a Keyup event for Enter key. This works for the most part for me. It doesn't work if the pasted content's length is higher than maxlength. 

Somewhere around line 242:
```js
input.on('paste', function (e) {
	setTimeout(() => {
		let keyupEvent = $.Event("keyup", {which: 13, keyCode: 13});
		$(this).trigger(keyupEvent);
	}, 0);
});
```

**Comment by fkranenburg** [comment]
Ok I can reproduce now.
