### ISSUE TITLE
Working on Tablet and Mobile phone

### ISSUE THREAD

**Issue by apeivandi** [fkranenburg/bootstrap-pincode-input#30]
Hi,
It seems the code works fine for desktop but when it's used on Android devices the rendering is messed up. I tested the same code on iPad and Mac and PC and Android chrome all worked fine except Android Chrome!
Any idea?

Amir

**Comment by fkranenburg** [comment]
Not sure what is exactly happening but can you test on the demo page? I see no issues on mobile android (chrome).

**Comment by apeivandi** [comment]
You're right! It works fine on your demo page but the page I've built shows the issue!
I'm trying to figure it up, maybe there is a confilict.
Here is my page www.noworkrewards.com and click on login
