### ISSUE TITLE
Paste with Ctrl + V

### ISSUE THREAD

**Issue by arielectron** [fkranenburg/bootstrap-pincode-input#31]
Hello.
I was thinking of adding the code of the Ctrl key in the if of keyup and keydown, but before doing it, I think it's prudent to check if it's not there for some reason.

**Comment by fkranenburg** [comment]
Some keys including Ctrl are not being accepted right now, but it should not be difficult to implement. I can't think of any good reason for this. If you have the time to implement it, I'll accept pull requests.

**Comment by arielectron** [comment]
ok thanks, these days I will be testing it, if everything works well, I will commit

**Comment by martingaudioso1990** [comment]
Hi, the paste method is skipped by keydown preventDefault. You need to add this line:

				}
				**else if (e.ctrlKey && e.keyCode === 86) {
					return;
				}**
				else {
					// in desktop mode, check if an number was entered

					if (!(e.keyCode == 8                            // backspace key
						|| e.keyCode == 9							// tab key
