### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by Nyariki** [fkranenburg/bootstrap-pincode-input#34]
How do you reset or clear the entered pin?

Let's say a user has submitted an incorrect pin. And you don't want them to hit backspace till they clear the entire input. 

I've tried `$('#input').val('');` and `$('#input').trigger(':reset');`. I'm using jquery. Am I missing something?

**Comment by fkranenburg** [comment]
Did you try the `clear` function?

**Comment by Nyariki** [comment]
Thanks. I'll try that.
