### ISSUE TITLE
Fails on touch devices if initialized while input is hidden

### ISSUE THREAD

**Issue by brucek2** [fkranenburg/bootstrap-pincode-input#39]
To reproduce:
1. Modify demo HTML so the input is initially hidden prior to initialization:
```
<div id="wrapper" style="display: none;">
    <input type="text" name="mycode" id="pincode-input1">
</div>
```

2. Modify demo JS so it is displayed following initialization:
```
$('#pincode-input1').pincodeInput({inputs:4});
$('#wrapper').css('display', 'block');
```

Observed:
- Entry works as normal on non-touch devices
- On touch devices (I tested on iPhone and Chrome debugger phone view): First digit is accepted and mask displayed. Subsequent digits are received and processed internally with no updates rendered on screen. The complete callback will be called once complete, although only the single digit will still be visible on the screen.

Comment:
- Current workaround is to initialize only while visible, although this is less ideal in that at least in my app, it can result in a visible on-screen change while the original input is transformed.

**Comment by fkranenburg** [comment]
While initializing some calculations are being run in the browser, e.g. the computed width and space available. This won't work if the parent is hidden with `display:none`. 

I'm not sure if it would fit your project but you could instead position the parent far out of the screen using absolute positioning and a `left: -9999px;`. This is just one way. Another way could be to set `visibility:hidden`, this way the component is not visible but takes space and space and width calculations won't probably fail.
