### ISSUE TITLE
On touch (only), digits flash/move on PIN completion

### ISSUE THREAD

**Issue by brucek2** [fkranenburg/bootstrap-pincode-input#40]
To Reproduce:
1. View the demo page on a touch device such as iPhone or Chrome debugger phone view
2. Enter 4 digits into the first example

Observed:
1. After the 4th digit is entered, all the digits briefly right-justify within their boxes, then snap back to the prior position. (touch only - does not happen in non-touch version.)
2. (In my app, a final line in the complete callback to focus the next input also fails, again on touch only, although I can't prove that's not an issue with my app.)

**Comment by fkranenburg** [comment]
> After the 4th digit is entered, all the digits briefly right-justify within their boxes, then snap back to the prior position. (touch only - does not happen in non-touch version.)

I wil investigate this. I think the current 'workaround' for limiting the amount of characters is causing this behouvior. Thanks for letting me know.

> (In my app, a final line in the complete callback to focus the next input also fails, again on touch only, although I can't prove that's not an issue with my app.)

The `complete` callback will fire before the above 'workaround' is running. One part of this workaround is a `blur()` and `select()` call on the input element, probably causing the issues in your app. You could workaround this for now by adding a `setTimeout` in the `complete` callback.

I will leave this issue open and try to fix this and find another workaround causing these issues.
