### ISSUE TITLE
Adjust letter spacing when the pincode is opened in a modal

### ISSUE THREAD

**Issue by papattes** [fkranenburg/bootstrap-pincode-input#41]
when adding a pin code in a modal asynchronously, the letter spacing is not taken into account because the rendering is not yet done when the JS code retrieves the width of input fields.

It would be good to make a detection of the location of the field and if it is in a modal, launch computation after the opening of the modal.

**Comment by fkranenburg** [comment]
It would be better to implement this detection inside your project. You could implement this yourself when the modal is loaded and visible.You need to initialize this widget then because it must be visibible in the browser.
