### ISSUE TITLE
no border = invisible input element on touch/modal case

### ISSUE THREAD

**Issue by brucek2** [fkranenburg/bootstrap-pincode-input#43]
I've tried the new version 3.0 and have run into an issue specific to the case where the input is on a touch device (iPhone or Chrome simulation for me), and is inside a bootstrap modal. On initialization, the input is briefly visible (meaning its border), but then disappears (meaning the border is styled to 0px). The input is still there and functional should the user be hardy enough to try it.

Sample html/js below. Please let me know if you need any more specifics. (and btw - thank you for the previous replies/fixes ;-)).

```
{{-- Bootstrap modal for PIN code entry --}}
<div id="modal-enter-pin" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">PIN Code Required</h4>
            </div>
            <div class="modal-body" style="width: 200px;">
                <input type="text" id="pin" name="pin" autocomplete="one-time-code">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
```

JS to display it:
```
var pinInit = false;        
$('#modal-enter-pin').on('shown.bs.modal', function (e) {
    if (!pinInit) {
        $('#pin').pincodeInput({
            inputs: 4,
            complete: handleModalSubmit
        });
        pinInit = true;
    }
}

$('#modal-enter-pin').modal('show');
```

**Comment by fkranenburg** [comment]
This is fixed in v3.0.1. Only a CSS update is needed. Here is [a working demo](http://fkranenburg.github.io/bootstrap-pincode-input/) of this component rendering in a Bootstrap modal (at the bottom of the page).
