### ISSUE TITLE
Problem with responsive

### ISSUE THREAD

**Issue by Droppix** [fkranenburg/bootstrap-pincode-input#49]
Hello,

I try your page 'http://fkranenburg.github.io/bootstrap-pincode-input', on mobile or responsive emulator chrome, there is an input problem.

**Comment by ferrykranenburgcw** [comment]
Just tried it on my mobile Android phone using Chrome. It still works. Could you explain was is happening?

**Comment by FerdinandFidel** [comment]
Here are also problems with responsive, the number is truncated a little bit, e.g. iPhoneX, iPhone5, iPhone 6,7,8, IPadPro and Galaxy S 3.

**Comment by fkranenburg** [comment]
I can't reproduce with Chrome devtools either. Please make sure to reload the page after switching to mobile, because other code is loaded for mobile devices.

**Comment by FerdinandFidel** [comment]
Ah sorry, it's a problem with the alphanumeric input. Does your solution support alphanumeric input ?

**Comment by ferrykranenburgcw** [comment]
No, only numeric digits are supported.
