### ISSUE TITLE
Switch inputs with LeftArrow/RightArrow keys

### ISSUE THREAD

**Issue by valichek** [fkranenburg/bootstrap-pincode-input#8]
Not possible to switch inputs with LeftArrow/RightArrow keys. It's very confusing

**Comment by fkranenburg** [comment]
I couldn't get this crossbrowser to work correcty. While inputting the input boxes are automatically focussed on desktop, and in touchmode it is only 1 input (this makes it hard). For now it only works like normal input elements. So users can use TAB and SHIFT+TAB for input switching.
